apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry-collector
  namespace: argocd
spec:
  sources:
  - repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    chart: opentelemetry-collector
    targetRevision: "0.131.0"
    helm:
      releaseName: opentelemetry-collector
      valueFiles:
      - $values/k8s/helm/otelvalues.yaml
      parameters:
      - name: image.repository
        value: "otel/opentelemetry-collector-k8s"
  - repoURL: https://github.com/louiscbrooks23/otel-profiling-test
    targetRevision: main
    ref: values
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
