apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pyroscope
  namespace: argocd
spec:
  destination:
    namespace: default
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: k8s/kustomize/pyroscope
    repoURL: https://github.com/louiscbrooks23/otel-profiling-test
    targetRevision: HEAD
