mode: deployment
command:
  extraArgs:
    - "--feature-gates=+service.profilesSupport"
config:
  exporters:
    debug:
      verbosity: detailed
    otlp:
      endpoint: pyroscope-service:4040
      tls:
        insecure: true
  extensions:
    health_check: {}
  processors:
    batch: {}
    memory_limiter:
      check_interval: 5s
      limit_percentage: 80
      spike_limit_percentage: 25
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: ${env:MY_POD_IP}:4317
        http:
          endpoint: ${env:MY_POD_IP}:4318
  service:
    extensions:
      - health_check
    pipelines:
      profiles:
        receivers:
          - otlp
        exporters:
          - debug
          - otlp
    telemetry:
      metrics:
        address: ${env:MY_POD_IP}:8888
service:
  type: LoadBalancer
