mode: deployment
command:
  extraArgs:
    - "--feature-gates=+service.profilesSupport"
config:
  exporters:
    debug:
      verbosity: detailed
    otlp:
      endpoint: pyroscope-service:4040
      tls:
        insecure: true
  extensions:
    health_check: {}
  processors:
    batch: {}
    memory_limiter:
      check_interval: 5s
      limit_percentage: 80
      spike_limit_percentage: 25
  receivers:
    zipkin:
    jaeger:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
  service:
    extensions:
      - health_check
    pipelines:
      metrics:
      logs:
      traces:
      profiles:
        receivers:
          - otlp
        exporters:
          - debug
          - otlp
service:
  type: LoadBalancer
